
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: video-match-cpu
  annotations:
    kubernetes.io/description: "Specialized NodePool for feature matching"
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 600s # scale down nodes after 10 minutes without workloads (excluding daemons)
  template:
    metadata:
      labels:
        pool-type: video-match-pipeline-pool
        node-type: video-match-cpu
      annotations:
        project: bda
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        name: big-ebs-100g
        kind: EC2NodeClass
      taints:
        - key: "s3gis.be/pool"
          value: "video-match-cpu"
          effect: "NoSchedule"
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - c6a
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: ["24xlarge"] 
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
  # weight: 10